name: Mirror Repository

on:
  push:
    branches:
      - main  # Change this to match your source branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/Rugum1/test_mirror_destination.git
          ref: main  # Change this to match your source branch

      - name: Push changes to destination repository
        run: |
          git remote add destination https://github.com/Rugum1/test_mirror_source.git
          git push destination main:main  # Change this to match your destination branch
